version: '3.8'

services:
  spring-boot-app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    # volumes:
    #   - ./home/borhan/Documents/docker_session/docker-compose/volume_data:/app  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/your_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
