name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Updated distribution name

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t demo .

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: your-dockerhub-username/demo:latest

      - name: Deploy to Production
        run: |
          # Example of deploying to a server or cloud provider
          # This step is highly specific to your deployment environment
          # For example, use SSH to copy the Docker image and run it


